package br.com.api.ghfluzao.enums;

public enum RolesUsuarios {
    
    ADMIN, //GERENCIAR USUARIOS DO SISTEMA
    FUNC_INEP, //CADASTRAR, EDITAR E EXLUIR QUESTOES REFERENTE A CURSO, PROVA, QUESTAO, OPÇÃO, GABARITO, PARTE E ASSUNTO
    PROFESSOR, // AVALIAR SE AS OPÇÕES DO SEU CURSO/TEMA ESTAO DE ACORDO COM A QUESTAO A A SER INSERIDA
    USER // APENAS BUSCAR INFORMAÇÕES 

}
